"""Task-specific configuration for Humathèque thesis metadata extraction."""

from __future__ import annotations

import json

DEFAULT_SOURCE_DATASET = "Geraldine/humatheque-vlm-sudoc-grounded"
DEFAULT_GROUND_TRUTH_COLUMN = "sudoc_record_templated"
DEFAULT_IMAGE_COLUMN = "image_uri"

THESIS_DEGREE_TYPE_VALUES = [
    "Thèse d'État",
    "Thèse de doctorat",
    "Thèse de 3e cycle",
    "Thèse d'université",
    "Thèse de docteur-ingénieur",
    "Thèse d'exercice",
]

OAI_DISCIPLINE_VALUES = [
    "Informatique, information, généralités",
    "Informatique",
    "Bibliothéconomie et sciences de l'information",
    "Organisations générales et muséologie",
    "Médias d'information, journalisme, édition",
    "Manuscrits et livres rares",
    "Philosophie, psychologie",
    "Métaphysique",
    "Epistémologie, causalité, genre humain",
    "Phénomènes paranormaux, pseudosciences",
    "Les divers systèmes et écoles philosophiques",
    "Psychologie",
    "Logique",
    "Morale (éthique)",
    "Philosophie de l'Antiquité, du Moyen Âge, de l'Orient",
    "Philosophie occidentale moderne et philosophies non orientales",
    "Religion",
    "Philosophie et théorie de la religion",
    "Bible",
    "Théologie chrétienne",
    "Théologie morale et pratiques chrétiennes",
    "Eglises locales, ordres religieux chrétiens",
    "Théologie chrétienne et société, ecclésiologie",
    "Histoire et géographie du christianisme et de l'Eglise chrétienne",
    "Confessions et sectes de l'Eglise chrétienne",
    "Autres religions",
    "Sciences sociales, sociologie, anthropologie",
    "Statistiques générales",
    "Science politique",
    "Economie",
    "Droit",
    "Administration publique. Arts et science militaires",
    "Problèmes et services sociaux",
    "Education et enseignement",
    "Commerce, communications, transports",
    "Ethnologie",
    "Langues et linguistique",
    "Linguistique générale",
    "Langue anglaise. Anglo-saxon",
    "Langues germaniques. Allemand",
    "Langues romanes. Français",
    "Langues italienne, roumaine, rhéto-romane",
    "Langues espagnole et portugaise",
    "Langues italiques. Latin",
    "Langues helléniques. Grec classique",
    "Autres langues",
    "Sciences de la nature et mathématiques",
    "Mathématiques",
    "Astronomie, cartographie, géodésie",
    "Physique",
    "Chimie, minéralogie, cristallographie",
    "Sciences de la terre",
    "Paléontologie. Paléozoologie",
    "Sciences de la vie, biologie, biochimie",
    "Plantes. Botanique",
    "Animaux. Zoologie",
    "Technologie (Sciences appliquées)",
    "Médecine et santé",
    "Sciences de l'ingénieur",
    "Agronomie, agriculture et médecine vétérinaire",
    "Economie domestique. Vie familiale",
    "Gestion et organisation de l'entreprise",
    "Génie chimique, technologies alimentaires",
    "Fabrication industrielle",
    "Fabrication de produits à usages spécifiques",
    "Bâtiments",
    "Arts. Beaux-arts et arts décoratifs",
    "Urbanisme",
    "Architecture",
    "Arts plastiques. Sculpture",
    "Dessin. Arts décoratifs",
    "Peinture",
    "Arts graphiques",
    "Photographie et les photographies, art numérique",
    "Musique",
    "Arts du spectacle, loisirs",
    "Sport",
    "Histoire et critique littéraires, rhétorique",
    "Littérature américaine en anglais",
    "Littératures anglaise et anglo-saxonne",
    "Littérature allemande",
    "Littérature de langues romanes. Littérature française",
    "Littérature italienne",
    "Littératures espagnole et portugaise",
    "Littérature latine",
    "Littérature grecque",
    "Littératures des autres langues",
    "Géographie et histoire",
    "Géographie et voyages",
    "Biographies générales, généalogie, emblèmes",
    "Histoire ancienne et préhistoire",
    "Histoire moderne et contemporaine de l'Europe",
    "Histoire générale de la France",
    "Histoire générale de l'Asie, Orient, Extrême-Orient",
    "Histoire générale de l'Afrique",
    "Histoire générale de l'Amérique du Nord",
    "Histoire générale de l'Amérique du Sud",
    "Histoire générale des autres parties du monde, des mondes extraterrestres. Iles du Pacifique",
]


def build_default_task_prompt() -> str:
    """Return the default extraction prompt for thesis metadata JSON output."""
    return f"""Extract the document title from this cover page.
Output ONLY valid JSON:
{{
  "title": "Main title of the thesis as it appears on the title page",
  "subtitle": "Subtitle or remainder of the title, usually following a colon; null if not present",
  "author": "Full name of the author (student) who wrote the thesis",
  "degree_type": "Academic degree sought by the author. Possible values are {json.dumps(THESIS_DEGREE_TYPE_VALUES, ensure_ascii=False)}",
  "discipline": "Academic field or discipline of the thesis.",
  "granting_institution": "Institution where the thesis was submitted and the degree is granted",
  "doctoral_school": "Doctoral school or graduate program, if explicitly mentioned",
  "defense_year": "Year the thesis was defended. Format yyyy",
  "thesis_advisor": "Main thesis advisor or supervisor",
  "jury_president": "President or chair of the thesis examination committee",
  "reviewers": "Reviewers or rapporteurs of the thesis. Use | as separator",
  "committee_members": "Other thesis committee or jury members. Use | as separator",
  "language": "Language in ISO 639-3 codes. Example: fre, eng, ita..."
}}"""
